anguage: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis Ci home of server
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r SpringBoot
  - mkdir -p deploy
  - mv SpringBoot.zip deploy/SpringBoot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEZY
    secret_access_key: $AWS_SECRET_KEY

    bucket: springboot-practice-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dudgh9661@gmail.com