anguage: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis Ci home of server
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dudgh9661@gmail.com